SETTINGS:
  DIRECTORY: "./oasis"
  PROJECT_NAME: "oasis_rotation_sigma10"
  NUM_WORKERS: 8

DATASET:
  SUBJECT_ID: "sub-OAS30433_ses-M066_run-02_T1w"
  LR_CONTRAST1: "axial_LR" # fixed
  LR_CONTRAST2: "rotated_coronal_LR" # moving

TRAINING:
  SEED: 12
  BATCH_SIZE: 50000
  LR: 0.0004
  OPTIM: "Adam"
  SHUFFLING: True
  LOSS: "MSELoss"
  # only one used at same time
  USE_MI: False
  USE_NMI: False
  USE_CC: True
  initial_generation_epochs: 15 #500 #50
  registration_epochs: 15 #250 #30
  generation_epochs: 15 #250 #40
  EARLY_STOPPING:
    ENABLED: True
    PATIENCE: 5 #10 # epochs to wait before stopping
    DELTA: 0.0005 #0.0001 # minimum improvement required
    DELTA_FRACTION: 0.1 #0.02 # minimum improvement required as a fraction of the best loss
    PATIENCE_REGISTRATION: 5 #15 # higher patience for registration phase
    PATIENCE_FINAL: 5 #10 # patience for final mixed training
    VERBOSE: True # print early stopping messages

GENERATION_MODEL:
  TYPE: "mlp"

REGISTRATION_MODEL:
  TYPE: "siren"
